### ISSUE TITLE
工作目录的问题

### ISSUE THREAD

**Issue by watry** [miswanting/Era.js#3]
我想从项目文件夹以外的位置启动Example.py：
<code>C:\>python xxx/Example.py</code>
但engine.py中，isdir、os.walk传入的是“data”这样的相对路径，所以找不到‘data’、‘plugin’等文件夹
<code>if not os.path.isdir(each):</code>
<code>for root, dirs, files in os.walk(path_to_folder):</code>

我试着用os.chdir改了工作目录，可以运行，见PR。但不知道有没有别的影响？

**Comment by miswanting** [comment]
没有影响，感谢提交PR
