### ISSUE TITLE
网站挂了，文档也看不了，求补

### ISSUE THREAD

**Issue by hubery055** [miswanting/Era.js#5]
网站挂了，文档也看不了，求补。最近才接触到era类游戏，看着之前的引擎确实很老了，而且不跨平台，想自己写一个。看到老哥已经写好了，来此学习一下。

**Comment by miswanting** [comment]
网站最近在变更，现在已放出了

**Comment by Jaykingamez** [comment]
![image](https://user-images.githubusercontent.com/39272482/182516761-54f60ee6-e79c-46b0-89ce-701262dae8f7.png)

http://erajs.net/ 网站好像有问题。

**Comment by miswanting** [comment]
> ![image](https://user-images.githubusercontent.com/39272482/182516761-54f60ee6-e79c-46b0-89ce-701262dae8f7.png)
> 
> http://erajs.net/ 网站好像有问题。

网站目前正在进行修改，未来会直接指向文档，还请耐心等待！
感谢对项目的关注！
